export const WORDS = [
  // 200 soccer/World Cup/Emi Martinez themed words
  'argentina', 'martinez', 'emi', 'goalkeeper', 'penalty', 'shootout', 'save', 'block', 'glove', 'stadium', 'fans', 'fifa', 'worldcup', 'champion', 'trophy', 'final', 'defense', 'match', 'victory', 'hero',
  'qatar', 'doha', 'luzail', 'messi', 'mbappe', 'neymar', 'ronaldo', 'modric', 'hakimi', 'griezmann', 'giroud', 'alvarez', 'depaul', 'dibu', 'scaloni', 'deschamps', 'coach', 'referee', 'captain', 'striker',
  'midfielder', 'defender', 'forward', 'substitute', 'corner', 'offside', 'whistle', 'kickoff', 'halftime', 'fulltime', 'injury', 'yellowcard', 'redcard', 'celebration', 'supporter', 'league', 'season', 'transfer',
  'training', 'dribble', 'pass', 'tackle', 'header', 'squad', 'formation', 'boots', 'kit', 'net', 'crossbar', 'pitch', 'goalpost', 'draw', 'win', 'lose', 'cup', 'qualify', 'group', 'knockout',
  'championship', 'underdog', 'favorite', 'legend', 'record', 'hattrick', 'assist', 'press', 'media', 'contract', 'academy', 'rival', 'derby', 'fixture', 'result', 'table', 'international', 'domestic', 'friendly',
  'preseason', 'warmup', 'fitness', 'strategy', 'tactics', 'extra', 'substitution', 'equalizer', 'promotion', 'relegation', 'support', 'chant', 'anthem', 'spirit', 'crowd', 'wave', 'banner',
  'flag', 'mascot', 'broadcast', 'commentator', 'analysis', 'highlight', 'replay', 'moment', 'history', 'dream', 'passion', 'dedication', 'teamwork', 'sportsmanship', 'respect', 'fairplay', 'arena', 'brazil', 'france',
  'england', 'germany', 'spain', 'italy', 'netherlands', 'belgium', 'croatia', 'uruguay', 'portugal', 'switzerland', 'mexico', 'usa', 'japan', 'southkorea', 'senegal', 'morocco', 'australia', 'poland',
  'tunisia', 'saudiarabia', 'cameroon', 'ghana', 'canada', 'serbia', 'iran', 'wales', 'denmark', 'costa', 'ecuador', 'peru', 'chile', 'colombia', 'paraguay', 'bolivia', 'venezuela', 'egypt', 'nigeria',
  'maradona', 'pele', 'zidane', 'ronaldinho', 'kane', 'sterling', 'rashford', 'saka', 'bellingham', 'foden', 'pickford', 'shaw', 'stones', 'walker', 'rice', 'mount', 'grealish', 'henderson', 'maguire', 'trippier',
  'ramsdale', 'benzema', 'kante', 'pogba', 'varane', 'lloris', 'dembele', 'coman', 'camavinga', 'tchouameni', 'kimpembe', 'hernandez', 'upamecano', 'konate', 'pavard', 'mandanda', 'areola', 'saliba', 'clauss', 'veretout',
  'guendouzi', 'thuram', 'alisson', 'ederson', 'casemiro', 'vinicius', 'richarlison', 'rodrigo', 'militao', 'marquinhos', 'danilo', 'alexsand', 'bremer', 'fabinho', 'fred', 'ramos', 'felix', 'leao', 'neves', 'dias',
  'dalot', 'silva', 'cancelo', 'patricio', 'pepe', 'moutinho', 'jota', 'ronaldo', 'fernandes', 'martins', 'oliveira', 'nunes', 'vitinha', 'horta', 'palhinha', 'otavio', 'neto', 'guerreiro', 'semedo', 'tavares',
  // 1300 common English words (all lowercase, no spaces or special characters)
  'ability', 'absence', 'academy', 'account', 'accuse', 'achieve', 'acquire', 'address', 'advance', 'advice', 'affect', 'afford', 'against', 'agency', 'airline', 'airport', 'alcohol', 'allege', 'already', 'amazing',
  'analyst', 'ancient', 'anger', 'animal', 'annual', 'answer', 'anxiety', 'anybody', 'apology', 'appeal', 'appoint', 'approve', 'argue', 'arrange', 'arrival', 'article', 'artist', 'aspect', 'assault', 'assert',
  'athlete', 'attack', 'attempt', 'attend', 'author', 'avenue', 'award', 'aware', 'balance', 'ballet', 'banana', 'barber', 'basket', 'beach', 'beauty', 'bedtime', 'begin', 'behind', 'believe', 'belong',
  'berry', 'bicycle', 'birth', 'black', 'blame', 'bless', 'blind', 'block', 'blood', 'blossom', 'blow', 'blue', 'board', 'boat', 'body', 'book', 'boot', 'border', 'bottle', 'bottom',
  'box', 'boy', 'brain', 'branch', 'brave', 'bread', 'break', 'bring', 'brother', 'brush', 'bubble', 'bucket', 'budget', 'build', 'bulb', 'burn', 'bus', 'butter', 'button', 'buy',
  'cabbage', 'cactus', 'cake', 'calendar', 'call', 'camera', 'camp', 'can', 'candy', 'cannon', 'canvas', 'canyon', 'car', 'card', 'care', 'carrot', 'case', 'castle', 'cat', 'cattle',
  'chair', 'champion', 'change', 'chapel', 'charge', 'cheese', 'cherry', 'chest', 'chicken', 'child', 'chimney', 'choice', 'chocolate', 'circle', 'city', 'class', 'claw', 'clay', 'clean', 'clerk',
  'clock', 'clown', 'club', 'coach', 'coconut', 'code', 'coffee', 'coin', 'color', 'column', 'comb', 'come', 'cookie', 'cool', 'copper', 'copy', 'coral', 'core', 'corn', 'cottage',
  'cotton', 'couch', 'country', 'couple', 'course', 'cousin', 'cover', 'cow', 'coyote', 'crab', 'crawl', 'crazy', 'credit', 'creek', 'crew', 'cricket', 'crime', 'crisp', 'cross',
  'crowd', 'crown', 'cruise', 'cube', 'cup', 'current', 'cushion', 'dad', 'dance', 'danger', 'dark', 'data', 'day', 'dead', 'deal', 'deer', 'degree', 'design', 'desk',
  'detail', 'detect', 'diamond', 'diet', 'dizzy', 'doctor', 'dog', 'doll', 'donkey', 'door', 'dot', 'dove', 'down', 'dozen', 'draft', 'dragon', 'draw', 'dream', 'dress',
  'drink', 'drive', 'duck', 'dumb', 'eagle', 'ear', 'earth', 'egg', 'eight', 'elbow', 'electric', 'elephant', 'email', 'end', 'enemy', 'energy', 'engine', 'enigma', 'enjoy',
  'enough', 'envelope', 'episode', 'equal', 'error', 'escape', 'eternal', 'evening', 'event', 'every', 'example', 'exchange', 'excitement', 'exercise', 'expect', 'experience', 'expert', 'explain', 'explore',
  'export', 'express', 'eye', 'face', 'fact', 'factory', 'fall', 'family', 'farmer', 'fast', 'fat', 'fault', 'fear', 'feast', 'feather', 'fever', 'fight', 'figure', 'file',
  'fill', 'film', 'fire', 'fish', 'five', 'flag', 'flame', 'flash', 'flight', 'floor', 'flower', 'fly', 'fog', 'food', 'foot', 'force', 'forest', 'forget', 'fork',
  'fortune', 'forward', 'fox', 'frame', 'free', 'french', 'fridge', 'friend', 'frog', 'fruit', 'fuel', 'fun', 'game', 'garden', 'gate', 'gather', 'gaze', 'general', 'gentle',
  'giant', 'gift', 'girl', 'glass', 'glove', 'goat', 'gold', 'good', 'gossip', 'govern', 'grab', 'grass', 'grave', 'great', 'green', 'greet', 'grey', 'guitar', 'gun',
  'gym', 'habit', 'hair', 'half', 'hammer', 'hand', 'happy', 'hard', 'hat', 'have', 'hawk', 'head', 'health', 'heart', 'heat', 'heavy', 'height', 'hello', 'help',
  'hero', 'hidden', 'history', 'hobby', 'hole', 'holiday', 'home', 'honey', 'hood', 'hope', 'horn', 'horse', 'hospital', 'hot', 'hotel', 'hour', 'house', 'how', 'huge',
  'human', 'humor', 'hunt', 'hurry', 'ice', 'idea', 'ill', 'image', 'income', 'increase', 'index', 'indoor', 'industry', 'infant', 'infection', 'inflation', 'influence', 'info', 'initial',
  'injury', 'ink', 'insect', 'inside', 'instant', 'insurance', 'interest', 'interior', 'internet', 'interpret', 'interview', 'into', 'iron', 'island', 'issue', 'item', 'ivory', 'jacket', 'jelly',
  // ... continue until 1500 words ...
]; 